import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // put the navbar somewhere in layout.tsx
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
