import '../styles/globals.css'

export const metadata = {
  title: 'MySmile - Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Put Next header here */}
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
